[package]
name = "infinite-client"
version.workspace = true
edition.workspace = true

[lib]
# 共有ライブラリとしてビルド
crate-type = ["cdylib"]

[dependencies]
lyon = "1.0.16"
xross-core = { workspace = true, features = ["xross-alloc"] }
