[toolchain]
channel = "nightly"
components = ["rust-src", "rust-analyzer", "rustfmt"]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    "aarch64-pc-windows-gnullvm",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]
